refactor: declarative component for home_dashboard
FlutterPlaza/FinFlow pull request #103
Opened 2023-02-27 15:01 UTC by DesmondTambe

## Description

This PR handles code refactoring for the dashboard screen.

- Global Nav header widget
- Cash balance widget
- Virtual card display
- Latest activities display

## Type of Change

- [x] ✨ New feature (non-breaking change which adds functionality)
- [ ] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [x] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [x] 🗑️ Chore

## Pre-launch Checklist

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I read and ran all relevant commands as specififed in the Running Tests section of the [Contributor Guide].
- [ ] The title of the PR follows the [Conventional Commits] guideline
- [ ] My local branch follows the naming standards in the [Deepsource Branch Naming Convention] or [Biodiversity Branch Naming Convention]
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy],
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] All existing and new tests are passing.

[Contributor Guide]: https://github.com/FlutterPlaza/.github/blob/main/CONTRIBUTING.md
[Conventional Commits]: https://www.conventionalcommits.org/en/v1.0.0-beta.4/
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[Biodiversity Branch Naming Convention]: https://bit.ly/3DyYSwM
[Deepsource Branch Naming Convention]: https://bit.ly/3Y08Gs4

2023-02-27 22:20 UTC, lkmandy requested changes
Hi @DesmondTambe 
I've left some feedback, please take a look and let me know if you have any questions or if you have any justifications why you took a particular approach

2023-02-27 22:20 UTC, lkmandy commented on lib/core/presentation/theming/themes/light_theme.dart
> +          .red, // set to odd color so we can see which component in the UI is affected
Can you put the comments above the related statement so that the formatting remains the same as in lines 20 - 24
e.g. 
```
// set to odd color so we can see which component in the UI is affected
onTertiary: Colors.red, 
```

2023-02-27 22:20 UTC, lkmandy commented on lib/authentication_with_facebook/infrastructure/facebook_auth_repository.dart
> +
Please remove this new line since this file is not a part of your implementation

2023-02-27 22:20 UTC, lkmandy commented on lib/authenticate_with_biometrics/view/biometric_button.dart
> +          color: Colors.grey,
This is the right formatting but again it's not part of your changes.
It'll be good to remove to space as well. We want just the files that contain your implementation to be a part of this PR

2023-02-27 22:20 UTC, lkmandy commented on lib/sign_in/view/widgets/phone_number_input.dart
> -
Remove this new change as well

2023-02-27 22:20 UTC, lkmandy commented on lib/home/view/user_search_screen.dart
> +import 'package:fpb/authentication_with_firebase/application/bloc/auth_bloc.dart';
- The search icon doesn't work on my end, so I'm unable to test the search feature. Is there a particualr reason why?
- The other components on the bottom navbar are invisible until you click on it as seen below.

![pr-rev](https://user-images.githubusercontent.com/17765231/221698378-8addce67-7c81-47ae-905b-81a9eb381dc3.jpeg)

2023-02-28 00:48 UTC, fonkamloic commented on lib/authenticate_with_biometrics/view/biometric_button.dart
> +          color: Colors.grey,
before pushing a project run 

flutter format lib test widgetbook packages

flutter analyze lib test widgetbook packages

new git add . 

add only specific files you modified.

2023-02-28 00:49 UTC, fonkamloic commented on lib/authentication_with_facebook/infrastructure/facebook_auth_repository.dart
>      } on SocketException catch (e) {
Do not commit unchanged files

2023-02-28 00:50 UTC, fonkamloic commented on lib/core/application/search_user_bloc/search_user_bloc.dart
> +        photo:
Search use wasn't support to be in this ticket. Please keep ticket straight to the point

2023-02-28 00:51 UTC, fonkamloic commented on lib/core/presentation/theming/colors/colors.dart
>    // static Color surfacerW = Color(0xffFFFFFF);
Why did you comment this out?

2023-02-28 00:51 UTC, fonkamloic commented on lib/core/presentation/theming/themes/light_theme.dart
> +          .green, // set to odd color so we can see which component in the UI is affected
Do not commit unmodified files

2023-02-28 00:54 UTC, fonkamloic commented on lib/home/view/dashboard.dart
> +          child: Scaffold(
Why do we need a scaffold?

2023-02-28 01:08 UTC, fonkamloic approved these changes
Merging and requesting changes.

2023-02-28 01:09 UTC, merged