feat: user profile screen
FlutterPlaza/FinFlow pull request #107
Opened 2023-03-01 15:07 UTC by TikuGaelle

## Description
 User profile screen.
  Solves issue #83 

## Type of Change

- [x] ✨ New feature (non-breaking change which adds functionality)
- [ ] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

## Pre-launch Checklist

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I read and ran all relevant commands as specififed in the Running Tests section of the [Contributor Guide].
- [ ] The title of the PR follows the [Conventional Commits] guideline
- [ ] My local branch follows the naming standards in the [Deepsource Branch Naming Convention] or [Biodiversity Branch Naming Convention]
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy],
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] All existing and new tests are passing.

[Contributor Guide]: https://github.com/FlutterPlaza/.github/blob/main/CONTRIBUTING.md
[Conventional Commits]: https://www.conventionalcommits.org/en/v1.0.0-beta.4/
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[Biodiversity Branch Naming Convention]: https://bit.ly/3DyYSwM
[Deepsource Branch Naming Convention]: https://bit.ly/3Y08Gs4

2023-03-02 09:05 UTC, fonkamloic commented on lib/core/presentation/theming/colors/colors.dart
> +  static Color onBgColorW = Color(0xffF5F5F5);
Have you tested the hold app to see how this color change affects the app?

2023-03-02 09:22 UTC, TikuGaelle commented on lib/core/presentation/theming/colors/colors.dart
> +  static Color onBgColorW = Color(0xffF5F5F5);
No. I changed that to make the grey texts visible on the background color.

2023-03-02 09:29 UTC, fonkamloic commented on lib/core/presentation/theming/colors/colors.dart
> +  static Color onBgColorW = Color(0xffF5F5F5);
Does it match the colors on Figma?

2023-03-03 08:00 UTC, TikuGaelle commented on lib/core/presentation/theming/colors/colors.dart
> +  static Color onBgColorW = Color(0xffF5F5F5);
Yes.

2023-03-03 12:48 UTC, lkmandy requested changes

2023-03-03 12:48 UTC, lkmandy commented on lib/profile/view/profile_page.dart
>              child: Column(
- Wrap your column in a `SingleChildScrollView()` to resolve the bottom overflow
- The Profile title should be increased too, `size: 32px, weight: 600 color: #181818`
- Also the screen background color should be htis shade of white `#F7F7F7` as on the design

![pr-rv2](https://user-images.githubusercontent.com/17765231/222723282-e2488ba1-11d2-4afa-a881-c05fafbe5556.jpeg)

2023-03-08 07:26 UTC, fonkamloic approved these changes

2023-03-08 07:27 UTC, merged