feat: Implement animated Pie scroll wheel
FlutterPlaza/FinFlow pull request #112
Opened 2023-03-03 10:01 UTC by DesmondTambe

## Description

- Implemented animated Pie scroll wheel (Circular slider widgets)
- Different budget categories
- Latest budget activities

Challenges:

- Adding multi-slider paints on the circular arc

## Type of Change

- [x] ✨ New feature (non-breaking change which adds functionality)
- [ ] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [x] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [x] 🗑️ Chore

## Pre-launch Checklist

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I read and ran all relevant commands as specififed in the Running Tests section of the [Contributor Guide].
- [ ] The title of the PR follows the [Conventional Commits] guideline
- [ ] My local branch follows the naming standards in the [Deepsource Branch Naming Convention] or [Biodiversity Branch Naming Convention]
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy],
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] All existing and new tests are passing.

[Contributor Guide]: https://github.com/FlutterPlaza/.github/blob/main/CONTRIBUTING.md
[Conventional Commits]: https://www.conventionalcommits.org/en/v1.0.0-beta.4/
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[Biodiversity Branch Naming Convention]: https://bit.ly/3DyYSwM
[Deepsource Branch Naming Convention]: https://bit.ly/3Y08Gs4

2023-03-03 11:50 UTC, lkmandy requested changes
Nice work @DesmondTambe 

- Please check out my ui related feedback to improve on a few more things
- Also there's a typo in your latest commit `fix: adjusted foramtter issue found in slider_utils.dart`  change  `foramtter ` to `formatted `

2023-03-03 11:50 UTC, lkmandy commented on lib/core/presentation/theming/themes/theme.dart
> +import 'package:flutter/services.dart';
This import isn't used within this file, please remove it

2023-03-03 11:50 UTC, lkmandy commented on lib/core/presentation/theming/themes/light_theme.dart
> +        color: _AppColors.greyLight,
- The greyLight color code doesn't match the two flavors on the design `#CACACA` and `#E0E0E0`
- `lightGrey` would make a better name

2023-03-03 11:50 UTC, lkmandy commented on lib/core/presentation/theming/themes/light_theme.dart
> +        color: _AppColors.greyLight,
- The app background color should be some shade of white `#F7F7F7` not the current greyish color
- The currency is missing the dollar sign as pointed out in the image
-  The like icon should be right-aligned not centered
- The New Category button should be black, not blue
- Is the pie chart currently able to represent different colors for different categories?

![pr-rv](https://user-images.githubusercontent.com/17765231/222711783-575291ae-9cba-40b4-add9-9b84d94779ee.jpeg)

2023-03-10 08:40 UTC, fonkamloic submitted a review, later dismissed

2023-03-10 08:42 UTC, merged