chore: Sign in page internalization
FlutterPlaza/FinFlow pull request #44
Opened 2023-01-30 22:02 UTC by TikuGaelle

## Description

Internalization of all string in Sign in page. First PR to solving issue #17 

## Type of Change

- [ ] ✨ New feature (non-breaking change which adds functionality)
- [ ] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [x] 🗑️ Chore

2023-01-31 05:30 UTC, fonkamloic requested changes
Please provide translations for the description in the `app_en.arb`
use deepl.com

2023-01-31 05:30 UTC, fonkamloic commented on lib/l10n/arb/app_fr.arb
> +        "description": "This is the title displayed on the sign in screen"
The translation of the description should also be in french

2023-01-31 05:30 UTC, fonkamloic commented on lib/l10n/arb/app_en.arb
> +        "description":"This is the text displayed on the sign in screen at the bottom of the page"
Use DeepL.com for translation instead of google translate for better results.

2023-01-31 08:32 UTC, TikuGaelle commented on lib/l10n/arb/app_en.arb
> +        "description":"This is the text displayed on the sign in screen at the bottom of the page"
Okay. Thanks

2023-02-02 18:52 UTC, lkmandy approved these changes

2023-02-02 18:52 UTC, lkmandy commented on lib/app/view/app.dart
> +
In the future, please note that It's good practice to avoid introducing changes that do not contribute to the solution or fix you're making.

2023-02-02 18:52 UTC, lkmandy commented on lib/l10n/arb/app_en.arb
> +        "description":"This is the label displayed on the sign in screen on the phone number tab"
Nice work @TikuGaelle 

Please kindly go through all the **.arb files** and add a space after the **description key**, just before the **value** in each case. e.g.  `"description":[put a space here]"This is the label displayed on the sign-in screen on the `phone number tab"

This will make all our key/value pair strings consistent.

2023-02-03 02:27 UTC, fonkamloic approved these changes

2023-02-03 02:27 UTC, merged