chore: Latest activities page internalization
FlutterPlaza/FinFlow pull request #47
Opened 2023-02-02 09:47 UTC by TikuGaelle

## Description

Latest activities page internalization in both english and french. PArt solution to #17 

## Type of Change

- [ ] ✨ New feature (non-breaking change which adds functionality)
- [ ] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [x] 🗑️ Chore

2023-02-02 19:32 UTC, lkmandy requested changes
Please make the white spacing after the description key consistent all through; changes need to be made in the app_en.arb and app_fr.arb files

2023-02-02 21:41 UTC, TikuGaelle commented
> Please make the white spacing after the description key consistent all through; changes need to be made in the app_en.arb and app_fr.arb files

Done. Thanks Amanda

2023-02-03 02:33 UTC, fonkamloic approved these changes

2023-02-03 02:37 UTC, fonkamloic approved these changes

2023-02-03 02:37 UTC, merged