fix: Home page VISA assets
FlutterPlaza/FinFlow pull request #53
Opened 2023-02-04 15:19 UTC by TikuGaelle

## Description

 * Additional Homepage assets, for VISA text. 

## Type of Change

- [ ] ✨ New feature (non-breaking change which adds functionality)
- [x] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read and ran all relevant commands as specififed in the Running Tests section of the [Contributor Guide].
- [x] The title of the PR follows the [Conventional Commits] guideline
- [x] My local branch follows the naming standards in the [Deepsource Branch Naming Convention] or [Biodiversity Branch Naming Convention]
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy],
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] All existing and new tests are passing.

[Contributor Guide]: https://github.com/FlutterPlaza/.github/blob/main/CONTRIBUTING.md
[Conventional Commits]: https://www.conventionalcommits.org/en/v1.0.0-beta.4/
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[Biodiversity Branch Naming Convention]: https://bit.ly/3DyYSwM
[Deepsource Branch Naming Convention]: https://bit.ly/3Y08Gs4

2023-02-07 11:12 UTC, lkmandy approved these changes

2023-02-08 03:17 UTC, fonkamloic commented
What issue is this pull request solving? 

You can't just create a pull request to add assets. 

Where is the rest of the code where the assets are being used? 

@TikuGaelle

2023-02-08 03:18 UTC, fonkamloic requested changes
Where is the code that uses the icons?

2023-02-09 08:19 UTC, TikuGaelle commented
> Where is the code that uses the icons?

It is the homepage, which has laready been merged. 
I did not want to push it again and have duplicate code.

2023-02-11 05:10 UTC, merged