feat: Phone number tab sign in UI with internationalization
FlutterPlaza/FinFlow pull request #65
Opened 2023-02-11 17:25 UTC by TikuGaelle

## Description

Sign in page phone number tab UI

<img src="https://user-images.githubusercontent.com/60433438/218272037-aa21da14-eed4-4207-9b08-0defeca17fc3.png ", width:500, height: 800>

![Screenshot_20230211-181302](https://user-images.githubusercontent.com/60433438/218272048-96bbc46d-2db5-497b-b6b8-d852271ce5d8.png)

## Type of Change

- [ ] ✨ New feature (non-breaking change which adds functionality)
- [ ] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

## Pre-launch Checklist

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I read and ran all relevant commands as specififed in the Running Tests section of the [Contributor Guide].
- [ ] The title of the PR follows the [Conventional Commits] guideline
- [ ] My local branch follows the naming standards in the [Deepsource Branch Naming Convention] or [Biodiversity Branch Naming Convention]
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy],
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] All existing and new tests are passing.

[Contributor Guide]: https://github.com/FlutterPlaza/.github/blob/main/CONTRIBUTING.md
[Conventional Commits]: https://www.conventionalcommits.org/en/v1.0.0-beta.4/
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[Biodiversity Branch Naming Convention]: https://bit.ly/3DyYSwM
[Deepsource Branch Naming Convention]: https://bit.ly/3Y08Gs4

2023-02-11 18:24 UTC, fonkamloic requested changes
Please resolve the merge conflicts first

2023-02-11 18:25 UTC, fonkamloic commented on lib/sign_in/view/sign_in_page.dart
> +                                      const PasswordInput(),
Export the PhoneInput as a component of widget the same way it is done with this passwordInput

2023-02-11 20:03 UTC, fonkamloic commented
<img width="850" alt="Screenshot 2023-02-11 at 3 03 02 PM" src="https://user-images.githubusercontent.com/23703424/218278858-be50cfb8-3a1a-4cb1-a856-92b53660561d.png">

let the implementation match the design

2023-02-15 21:52 UTC, lkmandy requested changes
The UI currently looks like this on my end

<img src="https://user-images.githubusercontent.com/17765231/219176352-21659acf-dc0a-41b9-9dba-fb99295688f4.jpg"  width="300" height="600">

Can you confirm that the UI displays properly on your end?

2023-02-16 04:24 UTC, TikuGaelle commented
> 



> The UI currently looks like this on my end
> 
> <img alt="" width="300" height="600" src="https://user-images.githubusercontent.com/17765231/219176352-21659acf-dc0a-41b9-9dba-fb99295688f4.jpg">
> 
> Can you confirm that the UI displays properly on your end?

Please run again now.

2023-02-16 15:40 UTC, lkmandy commented
@TikuGaelle 

The phone number section is missing and the UI is still alittle crunched at the level of the email title

<img src="https://user-images.githubusercontent.com/17765231/219413552-b599e74f-507e-4d4f-9603-252745b41fc8.jpeg" width="400" height="800">

<img src="https://user-images.githubusercontent.com/17765231/219413590-888a7452-7a19-4a1d-811d-6de1e4ff2234.jpeg" width="400" height="800">

2023-02-23 11:17 UTC, fonkamloic commented on lib/core/presentation/theming/themes/light_theme.dart
> +        color: Color(0xff808191)
No static colors in file. Colors will need to switch based on theme brightness. light or dark

2023-02-23 11:18 UTC, fonkamloic commented on lib/core/presentation/theming/themes/light_theme.dart
> +        color: Color(0xff808191)
define colors as part of colors file.

2023-02-23 11:21 UTC, fonkamloic commented on lib/core/presentation/widget/my_button.dart
> +      height: height ?? size.height * 0.065,
We have to change these values based on Screen dimensions.
small
small
large
xlarge
medium.

2023-02-23 11:24 UTC, fonkamloic commented on lib/onboarding/view/widgets/alternative_auth.dart
> +      Row(
Why the wrap?

2023-02-23 11:30 UTC, fonkamloic commented on lib/sign_in/view/sign_in_page.dart
> +                      child: ListView(children: [
Why listView?

2023-02-23 11:33 UTC, fonkamloic requested changes
Please just include the following files in PR
1- phone_number_input.dart
2- *.arb files
3- pubspec.yaml 

The other files will create a regression.

2023-02-24 07:58 UTC, TikuGaelle commented
> Please just include the following files in PR 1- phone_number_input.dart 2- *.arb files 3- pubspec.yaml
> 
> The other files will create a regression.

Okay.

2023-02-24 07:59 UTC, TikuGaelle commented on lib/sign_in/view/sign_in_page.dart
> +                      child: ListView(children: [
For Scrolling effect, which makes the design more responsive on all screen sizes...

2023-02-24 08:00 UTC, TikuGaelle commented on lib/onboarding/view/widgets/alternative_auth.dart
> +      Row(
Responsiveness to screen sizes of lesser width, which will make the icons move to the next line if it overflows

2023-02-24 08:01 UTC, TikuGaelle commented on lib/core/presentation/widget/my_button.dart
> +      height: height ?? size.height * 0.065,
Okay.

2023-02-24 08:01 UTC, TikuGaelle commented on lib/core/presentation/theming/themes/light_theme.dart
> +        color: Color(0xff808191)
Okay.

2023-02-26 02:32 UTC, fonkamloic approved these changes
LGTM

2023-02-26 02:32 UTC, merged