feat: biometric authentication WIP
FlutterPlaza/FinFlow pull request #78
Opened 2023-02-16 21:16 UTC by kefeh

Implement face ID/Touch ID login for users who have logged in to the application previously. This will provide a more secure and convenient login experience for users who have enabled face ID on their devices.

## Description

This pull request is opened to handle issue #26  and its a WIP so far.

### Still to be pushed
- implement local storage to store the credentials (password and email or phone number) to use when successful biometric auth
- Internationalise the strings used as guides on the UI

## Type of Change

- [ ] ✨ New feature (non-breaking change which adds functionality)
- [ ] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

## Pre-launch Checklist

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I read and ran all relevant commands as specififed in the Running Tests section of the [Contributor Guide].
- [ ] The title of the PR follows the [Conventional Commits] guideline
- [ ] My local branch follows the naming standards in the [Deepsource Branch Naming Convention] or [Biodiversity Branch Naming Convention]
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy],
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] All existing and new tests are passing.

[Contributor Guide]: https://github.com/FlutterPlaza/.github/blob/main/CONTRIBUTING.md
[Conventional Commits]: https://www.conventionalcommits.org/en/v1.0.0-beta.4/
[pub versioning philosophy]: https://dart.dev/tools/pub/versioning
[Biodiversity Branch Naming Convention]: https://bit.ly/3DyYSwM
[Deepsource Branch Naming Convention]: https://bit.ly/3Y08Gs4

2023-02-18 04:49 UTC, fonkamloic commented on android/app/build.gradle
> +}
Please add documentation when you add a configuration. Provide proper comment documentation for the propose of the addition.

2023-02-18 04:52 UTC, fonkamloic commented on lib/authenticate_with_biometrics/application/bloc/biometric_auth_bloc.dart
> +    } on PlatformException {
Any exception thrown here is not handled.
Please handle the exception and provide a message to notify the UI

2023-02-18 04:55 UTC, fonkamloic commented on lib/authenticate_with_biometrics/application/bloc/biometric_auth_bloc.dart
> +            'Scan your fingerprint (or face or whatever) to authenticate',
use platform isOS to display specific message for android and IOs

2023-02-18 04:55 UTC, fonkamloic commented on lib/authenticate_with_biometrics/application/bloc/biometric_auth_bloc.dart
> +    } on PlatformException {
Handle exeception

2023-02-18 04:59 UTC, fonkamloic requested changes
Good WIP 👍

2023-02-18 11:25 UTC, kefeh commented on lib/authenticate_with_biometrics/application/bloc/biometric_auth_bloc.dart
> +            'Scan your fingerprint (or face or whatever) to authenticate',
Will do just that

2023-02-18 11:27 UTC, kefeh commented on lib/authenticate_with_biometrics/application/bloc/biometric_auth_bloc.dart
> +    } on PlatformException {
Yeah that is why I asked what we have for pop up notifications in the app to handle this. Can you point me out to something we have so far and we can replace it with something appropriate ( or should I just use a basic snackbar?)

2023-02-18 14:52 UTC, fonkamloic commented on lib/authenticate_with_biometrics/application/bloc/biometric_auth_bloc.dart
> +    } on PlatformException {
Please check the architecture of the implementation of other features eg authentication_with_google 

The exception where handled at first but not linked to the presentation layer. Now there are at least to the signin_page or signup page

2023-02-18 19:46 UTC, fonkamloic commented
Also, please link the issue you are solving

2023-02-20 05:36 UTC, kefeh commented on lib/authenticate_with_biometrics/application/bloc/biometric_auth_bloc.dart
> +    } on PlatformException {
Thanks, will do

2023-02-20 08:48 UTC, fonkamloic commented on android/app/src/main/kotlin/com/flutterplaza/MainActivity.kt
>  }
Why do we need a fragment activities? 
Please document the code properly so that everyone could learn from it.

2023-02-20 09:22 UTC, kefeh commented on android/app/src/main/kotlin/com/flutterplaza/MainActivity.kt
>  }
Added the documentation in the Manifest file in the current update.

2023-02-20 09:34 UTC, fonkamloic commented on android/app/src/main/AndroidManifest.xml
> +   <uses-permission android:name="android.permission.USE_FINGERPRINT"/>
With the recent changes in kotlin dev, do we need to specifically add permission import? 

Just curious don't actually know

2023-02-20 09:50 UTC, kefeh commented on android/app/src/main/AndroidManifest.xml
> +   <uses-permission android:name="android.permission.USE_FINGERPRINT"/>
I honestly don't know, but for safekeeping lets just leave it there until we confidently can remove it

2023-02-26 03:22 UTC, fonkamloic approved these changes
LGTM

2023-02-26 03:22 UTC, merged